{
 "title": "Home",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "s21_ram_usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    { "expr": "    s21_ram_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "s21_disk_usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 0 },
   "targets": [
    { "expr": "    s21_disk_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "s21_cpu_usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "    s21_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "welcome",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gettingstarted",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest from the blog",
   "type": "news",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {}
   ]
  }
 ]
}