global:
  scrape_interval:     3s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

